/*
 * SoundCloud Public API Specification
 * Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateUpdatePlaylistFormRequest
 */
public class CreateUpdatePlaylistFormRequestTest {
    private final CreateUpdatePlaylistFormRequest model = new CreateUpdatePlaylistFormRequest();

    /**
     * Model tests for CreateUpdatePlaylistFormRequest
     */
    @Test
    public void testCreateUpdatePlaylistFormRequest() {
        // TODO: test CreateUpdatePlaylistFormRequest
    }

    /**
     * Test the property 'playlistTitle'
     */
    @Test
    public void playlistTitleTest() {
        // TODO: test playlistTitle
    }

    /**
     * Test the property 'playlistSharing'
     */
    @Test
    public void playlistSharingTest() {
        // TODO: test playlistSharing
    }

    /**
     * Test the property 'playlistDescription'
     */
    @Test
    public void playlistDescriptionTest() {
        // TODO: test playlistDescription
    }

    /**
     * Test the property 'playlistTracksId'
     */
    @Test
    public void playlistTracksIdTest() {
        // TODO: test playlistTracksId
    }

    /**
     * Test the property 'playlistArtworkData'
     */
    @Test
    public void playlistArtworkDataTest() {
        // TODO: test playlistArtworkData
    }

    /**
     * Test the property 'playlistEan'
     */
    @Test
    public void playlistEanTest() {
        // TODO: test playlistEan
    }

    /**
     * Test the property 'playlistGenre'
     */
    @Test
    public void playlistGenreTest() {
        // TODO: test playlistGenre
    }

    /**
     * Test the property 'playlistLabelName'
     */
    @Test
    public void playlistLabelNameTest() {
        // TODO: test playlistLabelName
    }

    /**
     * Test the property 'playlistLicense'
     */
    @Test
    public void playlistLicenseTest() {
        // TODO: test playlistLicense
    }

    /**
     * Test the property 'playlistPermalink'
     */
    @Test
    public void playlistPermalinkTest() {
        // TODO: test playlistPermalink
    }

    /**
     * Test the property 'playlistPermalinkUrl'
     */
    @Test
    public void playlistPermalinkUrlTest() {
        // TODO: test playlistPermalinkUrl
    }

    /**
     * Test the property 'playlistPurchaseTitle'
     */
    @Test
    public void playlistPurchaseTitleTest() {
        // TODO: test playlistPurchaseTitle
    }

    /**
     * Test the property 'playlistPurchaseUrl'
     */
    @Test
    public void playlistPurchaseUrlTest() {
        // TODO: test playlistPurchaseUrl
    }

    /**
     * Test the property 'playlistRelease'
     */
    @Test
    public void playlistReleaseTest() {
        // TODO: test playlistRelease
    }

    /**
     * Test the property 'playlistReleaseDate'
     */
    @Test
    public void playlistReleaseDateTest() {
        // TODO: test playlistReleaseDate
    }

    /**
     * Test the property 'playlistSetType'
     */
    @Test
    public void playlistSetTypeTest() {
        // TODO: test playlistSetType
    }

    /**
     * Test the property 'playlistTagList'
     */
    @Test
    public void playlistTagListTest() {
        // TODO: test playlistTagList
    }

}
