/*
 * SoundCloud Public API Specification
 * Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeQuota
 */
public class MeQuotaTest {
    private final MeQuota model = new MeQuota();

    /**
     * Model tests for MeQuota
     */
    @Test
    public void testMeQuota() {
        // TODO: test MeQuota
    }

    /**
     * Test the property 'unlimitedUploadQuota'
     */
    @Test
    public void unlimitedUploadQuotaTest() {
        // TODO: test unlimitedUploadQuota
    }

    /**
     * Test the property 'uploadSecondsUsed'
     */
    @Test
    public void uploadSecondsUsedTest() {
        // TODO: test uploadSecondsUsed
    }

    /**
     * Test the property 'uploadSecondsLeft'
     */
    @Test
    public void uploadSecondsLeftTest() {
        // TODO: test uploadSecondsLeft
    }

}
