/*
 * SoundCloud Public API Specification
 * Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Track;
import com.konfigthis.client.model.TrackLabel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TP
 */
public class TPTest {
    private final TP model = new TP();

    /**
     * Model tests for TP
     */
    @Test
    public void testTP() {
        // TODO: test TP
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'artworkUrl'
     */
    @Test
    public void artworkUrlTest() {
        // TODO: test artworkUrl
    }

    /**
     * Test the property 'bpm'
     */
    @Test
    public void bpmTest() {
        // TODO: test bpm
    }

    /**
     * Test the property 'commentCount'
     */
    @Test
    public void commentCountTest() {
        // TODO: test commentCount
    }

    /**
     * Test the property 'commentable'
     */
    @Test
    public void commentableTest() {
        // TODO: test commentable
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'downloadCount'
     */
    @Test
    public void downloadCountTest() {
        // TODO: test downloadCount
    }

    /**
     * Test the property 'downloadable'
     */
    @Test
    public void downloadableTest() {
        // TODO: test downloadable
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'embeddableBy'
     */
    @Test
    public void embeddableByTest() {
        // TODO: test embeddableBy
    }

    /**
     * Test the property 'favoritingsCount'
     */
    @Test
    public void favoritingsCountTest() {
        // TODO: test favoritingsCount
    }

    /**
     * Test the property 'genre'
     */
    @Test
    public void genreTest() {
        // TODO: test genre
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isrc'
     */
    @Test
    public void isrcTest() {
        // TODO: test isrc
    }

    /**
     * Test the property 'keySignature'
     */
    @Test
    public void keySignatureTest() {
        // TODO: test keySignature
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'labelName'
     */
    @Test
    public void labelNameTest() {
        // TODO: test labelName
    }

    /**
     * Test the property 'license'
     */
    @Test
    public void licenseTest() {
        // TODO: test license
    }

    /**
     * Test the property 'permalinkUrl'
     */
    @Test
    public void permalinkUrlTest() {
        // TODO: test permalinkUrl
    }

    /**
     * Test the property 'playbackCount'
     */
    @Test
    public void playbackCountTest() {
        // TODO: test playbackCount
    }

    /**
     * Test the property 'purchaseTitle'
     */
    @Test
    public void purchaseTitleTest() {
        // TODO: test purchaseTitle
    }

    /**
     * Test the property 'purchaseUrl'
     */
    @Test
    public void purchaseUrlTest() {
        // TODO: test purchaseUrl
    }

    /**
     * Test the property 'release'
     */
    @Test
    public void releaseTest() {
        // TODO: test release
    }

    /**
     * Test the property 'releaseDay'
     */
    @Test
    public void releaseDayTest() {
        // TODO: test releaseDay
    }

    /**
     * Test the property 'releaseMonth'
     */
    @Test
    public void releaseMonthTest() {
        // TODO: test releaseMonth
    }

    /**
     * Test the property 'releaseYear'
     */
    @Test
    public void releaseYearTest() {
        // TODO: test releaseYear
    }

    /**
     * Test the property 'sharing'
     */
    @Test
    public void sharingTest() {
        // TODO: test sharing
    }

    /**
     * Test the property 'streamUrl'
     */
    @Test
    public void streamUrlTest() {
        // TODO: test streamUrl
    }

    /**
     * Test the property 'streamable'
     */
    @Test
    public void streamableTest() {
        // TODO: test streamable
    }

    /**
     * Test the property 'tagList'
     */
    @Test
    public void tagListTest() {
        // TODO: test tagList
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'userFavorite'
     */
    @Test
    public void userFavoriteTest() {
        // TODO: test userFavorite
    }

    /**
     * Test the property 'userPlaybackCount'
     */
    @Test
    public void userPlaybackCountTest() {
        // TODO: test userPlaybackCount
    }

    /**
     * Test the property 'waveformUrl'
     */
    @Test
    public void waveformUrlTest() {
        // TODO: test waveformUrl
    }

    /**
     * Test the property 'availableCountryCodes'
     */
    @Test
    public void availableCountryCodesTest() {
        // TODO: test availableCountryCodes
    }

    /**
     * Test the property 'access'
     */
    @Test
    public void accessTest() {
        // TODO: test access
    }

    /**
     * Test the property 'downloadUrl'
     */
    @Test
    public void downloadUrlTest() {
        // TODO: test downloadUrl
    }

    /**
     * Test the property 'repostsCount'
     */
    @Test
    public void repostsCountTest() {
        // TODO: test repostsCount
    }

    /**
     * Test the property 'secretUri'
     */
    @Test
    public void secretUriTest() {
        // TODO: test secretUri
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'ean'
     */
    @Test
    public void eanTest() {
        // TODO: test ean
    }

    /**
     * Test the property 'labelId'
     */
    @Test
    public void labelIdTest() {
        // TODO: test labelId
    }

    /**
     * Test the property 'lastModified'
     */
    @Test
    public void lastModifiedTest() {
        // TODO: test lastModified
    }

    /**
     * Test the property 'permalink'
     */
    @Test
    public void permalinkTest() {
        // TODO: test permalink
    }

    /**
     * Test the property 'playlistType'
     */
    @Test
    public void playlistTypeTest() {
        // TODO: test playlistType
    }

    /**
     * Test the property 'trackCount'
     */
    @Test
    public void trackCountTest() {
        // TODO: test trackCount
    }

    /**
     * Test the property 'tracks'
     */
    @Test
    public void tracksTest() {
        // TODO: test tracks
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'likesCount'
     */
    @Test
    public void likesCountTest() {
        // TODO: test likesCount
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'tracksUri'
     */
    @Test
    public void tracksUriTest() {
        // TODO: test tracksUri
    }

}
