/*
 * SoundCloud Public API Specification
 * Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UserSubscriptionsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TrackLabel
 */
public class TrackLabelTest {
    private final TrackLabel model = new TrackLabel();

    /**
     * Model tests for TrackLabel
     */
    @Test
    public void testTrackLabel() {
        // TODO: test TrackLabel
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'avatarUrl'
     */
    @Test
    public void avatarUrlTest() {
        // TODO: test avatarUrl
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'discogsName'
     */
    @Test
    public void discogsNameTest() {
        // TODO: test discogsName
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'followersCount'
     */
    @Test
    public void followersCountTest() {
        // TODO: test followersCount
    }

    /**
     * Test the property 'followingsCount'
     */
    @Test
    public void followingsCountTest() {
        // TODO: test followingsCount
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'lastModified'
     */
    @Test
    public void lastModifiedTest() {
        // TODO: test lastModified
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'myspaceName'
     */
    @Test
    public void myspaceNameTest() {
        // TODO: test myspaceName
    }

    /**
     * Test the property 'permalink'
     */
    @Test
    public void permalinkTest() {
        // TODO: test permalink
    }

    /**
     * Test the property 'permalinkUrl'
     */
    @Test
    public void permalinkUrlTest() {
        // TODO: test permalinkUrl
    }

    /**
     * Test the property 'plan'
     */
    @Test
    public void planTest() {
        // TODO: test plan
    }

    /**
     * Test the property 'playlistCount'
     */
    @Test
    public void playlistCountTest() {
        // TODO: test playlistCount
    }

    /**
     * Test the property 'publicFavoritesCount'
     */
    @Test
    public void publicFavoritesCountTest() {
        // TODO: test publicFavoritesCount
    }

    /**
     * Test the property 'repostsCount'
     */
    @Test
    public void repostsCountTest() {
        // TODO: test repostsCount
    }

    /**
     * Test the property 'trackCount'
     */
    @Test
    public void trackCountTest() {
        // TODO: test trackCount
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'websiteTitle'
     */
    @Test
    public void websiteTitleTest() {
        // TODO: test websiteTitle
    }

    /**
     * Test the property 'subscriptions'
     */
    @Test
    public void subscriptionsTest() {
        // TODO: test subscriptions
    }

}
