/*
 * SoundCloud Public API Specification
 * Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Track;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Tracks
 */
public class TracksTest {
    private final Tracks model = new Tracks();

    /**
     * Model tests for Tracks
     */
    @Test
    public void testTracks() {
        // TODO: test Tracks
    }

    /**
     * Test the property 'collection'
     */
    @Test
    public void collectionTest() {
        // TODO: test collection
    }

    /**
     * Test the property 'nextHref'
     */
    @Test
    public void nextHrefTest() {
        // TODO: test nextHref
    }

}
