/*
 * SoundCloud Public API Specification
 * Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TrackMetadataRequestTrack;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TrackMetadataRequest
 */
public class TrackMetadataRequestTest {
    private final TrackMetadataRequest model = new TrackMetadataRequest();

    /**
     * Model tests for TrackMetadataRequest
     */
    @Test
    public void testTrackMetadataRequest() {
        // TODO: test TrackMetadataRequest
    }

    /**
     * Test the property 'track'
     */
    @Test
    public void trackTest() {
        // TODO: test track
    }

}
