/*
 * SoundCloud Public API Specification
 * Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Streams
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Streams {
  public static final String SERIALIZED_NAME_HTTP_MP3128_URL = "http_mp3_128_url";
  @SerializedName(SERIALIZED_NAME_HTTP_MP3128_URL)
  private String httpMp3128Url;

  public static final String SERIALIZED_NAME_HLS_MP3128_URL = "hls_mp3_128_url";
  @SerializedName(SERIALIZED_NAME_HLS_MP3128_URL)
  private String hlsMp3128Url;

  public static final String SERIALIZED_NAME_HLS_OPUS64_URL = "hls_opus_64_url";
  @SerializedName(SERIALIZED_NAME_HLS_OPUS64_URL)
  private String hlsOpus64Url;

  public static final String SERIALIZED_NAME_PREVIEW_MP3128_URL = "preview_mp3_128_url";
  @SerializedName(SERIALIZED_NAME_PREVIEW_MP3128_URL)
  private String previewMp3128Url;

  public Streams() {
  }

  public Streams httpMp3128Url(String httpMp3128Url) {
    
    
    
    
    this.httpMp3128Url = httpMp3128Url;
    return this;
  }

   /**
   * Get httpMp3128Url
   * @return httpMp3128Url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHttpMp3128Url() {
    return httpMp3128Url;
  }


  public void setHttpMp3128Url(String httpMp3128Url) {
    
    
    
    this.httpMp3128Url = httpMp3128Url;
  }


  public Streams hlsMp3128Url(String hlsMp3128Url) {
    
    
    
    
    this.hlsMp3128Url = hlsMp3128Url;
    return this;
  }

   /**
   * Get hlsMp3128Url
   * @return hlsMp3128Url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHlsMp3128Url() {
    return hlsMp3128Url;
  }


  public void setHlsMp3128Url(String hlsMp3128Url) {
    
    
    
    this.hlsMp3128Url = hlsMp3128Url;
  }


  public Streams hlsOpus64Url(String hlsOpus64Url) {
    
    
    
    
    this.hlsOpus64Url = hlsOpus64Url;
    return this;
  }

   /**
   * Get hlsOpus64Url
   * @return hlsOpus64Url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHlsOpus64Url() {
    return hlsOpus64Url;
  }


  public void setHlsOpus64Url(String hlsOpus64Url) {
    
    
    
    this.hlsOpus64Url = hlsOpus64Url;
  }


  public Streams previewMp3128Url(String previewMp3128Url) {
    
    
    
    
    this.previewMp3128Url = previewMp3128Url;
    return this;
  }

   /**
   * Get previewMp3128Url
   * @return previewMp3128Url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPreviewMp3128Url() {
    return previewMp3128Url;
  }


  public void setPreviewMp3128Url(String previewMp3128Url) {
    
    
    
    this.previewMp3128Url = previewMp3128Url;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Streams instance itself
   */
  public Streams putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Streams streams = (Streams) o;
    return Objects.equals(this.httpMp3128Url, streams.httpMp3128Url) &&
        Objects.equals(this.hlsMp3128Url, streams.hlsMp3128Url) &&
        Objects.equals(this.hlsOpus64Url, streams.hlsOpus64Url) &&
        Objects.equals(this.previewMp3128Url, streams.previewMp3128Url)&&
        Objects.equals(this.additionalProperties, streams.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(httpMp3128Url, hlsMp3128Url, hlsOpus64Url, previewMp3128Url, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Streams {\n");
    sb.append("    httpMp3128Url: ").append(toIndentedString(httpMp3128Url)).append("\n");
    sb.append("    hlsMp3128Url: ").append(toIndentedString(hlsMp3128Url)).append("\n");
    sb.append("    hlsOpus64Url: ").append(toIndentedString(hlsOpus64Url)).append("\n");
    sb.append("    previewMp3128Url: ").append(toIndentedString(previewMp3128Url)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("http_mp3_128_url");
    openapiFields.add("hls_mp3_128_url");
    openapiFields.add("hls_opus_64_url");
    openapiFields.add("preview_mp3_128_url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Streams
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Streams.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Streams is not found in the empty JSON string", Streams.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("http_mp3_128_url") != null && !jsonObj.get("http_mp3_128_url").isJsonNull()) && !jsonObj.get("http_mp3_128_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `http_mp3_128_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("http_mp3_128_url").toString()));
      }
      if ((jsonObj.get("hls_mp3_128_url") != null && !jsonObj.get("hls_mp3_128_url").isJsonNull()) && !jsonObj.get("hls_mp3_128_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hls_mp3_128_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hls_mp3_128_url").toString()));
      }
      if ((jsonObj.get("hls_opus_64_url") != null && !jsonObj.get("hls_opus_64_url").isJsonNull()) && !jsonObj.get("hls_opus_64_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hls_opus_64_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hls_opus_64_url").toString()));
      }
      if ((jsonObj.get("preview_mp3_128_url") != null && !jsonObj.get("preview_mp3_128_url").isJsonNull()) && !jsonObj.get("preview_mp3_128_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `preview_mp3_128_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("preview_mp3_128_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Streams.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Streams' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Streams> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Streams.class));

       return (TypeAdapter<T>) new TypeAdapter<Streams>() {
           @Override
           public void write(JsonWriter out, Streams value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Streams read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Streams instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Streams given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Streams
  * @throws IOException if the JSON string is invalid with respect to Streams
  */
  public static Streams fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Streams.class);
  }

 /**
  * Convert an instance of Streams to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

