/*
 * SoundCloud Public API Specification
 * Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LikesApi
 */
@Disabled
public class LikesApiTest {

    private static LikesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new LikesApi(apiClient);
    }

    /**
     * Likes a playlist.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void playlistTest() throws ApiException {
        Integer playlistId = null;
        api.playlist(playlistId)
                .execute();
        // TODO: test validations
    }

    /**
     * Likes a track.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void trackActionTest() throws ApiException {
        Integer trackId = null;
        api.trackAction(trackId)
                .execute();
        // TODO: test validations
    }

    /**
     * Unlikes a playlist.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unlikePlaylistTest() throws ApiException {
        Integer playlistId = null;
        api.unlikePlaylist(playlistId)
                .execute();
        // TODO: test validations
    }

    /**
     * Unlikes a track.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unlikeTrackTest() throws ApiException {
        Integer trackId = null;
        api.unlikeTrack(trackId)
                .execute();
        // TODO: test validations
    }

}
