/*
 * SoundCloud Public API Specification
 * Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MiscellaneousApi
 */
@Disabled
public class MiscellaneousApiTest {

    private static MiscellaneousApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new MiscellaneousApi(apiClient);
    }

    /**
     * Resolves soundcloud.com and on.soundcloud.com URLs to Resource URLs to use with the API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resolveSoundcloudUrlsTest() throws ApiException {
        String url = null;
        api.resolveSoundcloudUrls(url)
                .execute();
        // TODO: test validations
    }

}
